### ISSUE TITLE
在AStar中 没有维护maps数组属性,同样没有维护end node,怎么test测试类里可以打印maps呢

### ISSUE THREAD

**Issue by notcaremath** [ClaymanTwinkle/astar#2]

**Comment by notcaremath** [comment]
/**
     * 移动当前结点
     */
    private void moveNodes(MapInfo mapInfo)
    {
        Node current=null;
        while (!openList.isEmpty())
        {
            if (isCoordInClose(mapInfo.end.coord))
            {
                drawPath(mapInfo.maps, mapInfo.end);
                break;
            }
            current = openList.poll();
            closeList.add(current);
            addNeighborNodeInOpen(mapInfo,current);
        }
        System.out.println(current.coord);
    }

}

该方法,  current = openList.poll();如果compare Note比较的F值如果相等,会不会相当于自动放弃一条可能正确的路线

**Comment by ClaymanTwinkle** [comment]
![image](https://user-images.githubusercontent.com/15152514/78969043-98ca4800-7b38-11ea-8862-c3c0d537ed14.png)
这里传进去了。
