### ISSUE TITLE
难道没人发现你这个H值没有乘代价(*10)吗，会导致一半的路寻不到，且增加消耗

### ISSUE THREAD

**Issue by wushu037** [ClaymanTwinkle/astar#3]
![image](https://user-images.githubusercontent.com/61787040/127264866-608148a9-adf4-40bf-93ce-32123e354c95.png)

![image](https://user-images.githubusercontent.com/61787040/127264828-7d54be13-771b-4ec2-a1e3-cad2c34bde5f.png)

https://blog.csdn.net/qq_43413788/article/details/108630704
我这篇博客里有分析，如果我错了请指正

**Comment by ClaymanTwinkle** [comment]
已经修复了不是这个问题

**Comment by wushu037** [comment]
摘自：#1 
和作者进行了讨论后，解决了这个问题。==**感谢作者还在维护这个项目**==😊
![image](https://user-images.githubusercontent.com/61787040/127304560-5c445e5c-3e70-46b3-817f-d6c46cfa9587.png)

现在百度搜索到的Java-astar很多权重比较高的结果都是直接copy的此仓库之前错误的代码，会造成使用中的错误

希望作者能把这两个issue打开，closed的状态很容易会让人忽略有用的issue

这样能够尽量让其他人使用时或者回来找问题时更清晰明白
